/*********************Program_9_1**************************/
PROC FORMAT;
VALUE AGEft     4="4 WEEKS OLD"
                6="6 WEEKS OLD"
                8="8 WEEKS OLD"
                10="10 WEEKS OLD"
                12="12 WEEKS OLD";
RUN;

DATA PUMPKIN;
INFILE "/folders/myfolders/data/PUMPKIN.txt" dlm=' ';
DO PUMPKIM=1 TO 24;
    DO AGE= 4 TO 12 by 2;
        AGESQ=AGE**2;
        AGECU=AGE**3;
        INPUT WEIGHT @@;
        OUTPUT;
    END;
END;
FORMAT AGE  AGEft.;

*SCATTER PLOT OF THE ORIGINAL DATA;
Ods Graphics On;

TITLE "SCATTER PLOT OF  WEIGHT_VS_AGE OF PUMPKINS";
proc sgplot data=PUMPKIN;
scatter x=WEIGHT y=AGE;
run;

*LINEAR MODEL;
PROC REG DATA=PUMPKIN ;
MODEL WEIGHT=AGE;
OUTPUT OUT=PUMPKIN_LINEAR P=yhat;
TITLE "LINEAR REGRESSION FOR WEIGHT_VS_AGE OF PUMPKINS";
RUN;

*POLYNOMIAL MODEL;
PROC REG DATA=PUMPKIN  PLOTS=PREDICTIONS(X=AGE);
MODEL WEIGHT = AGE AGESQ AGECU;
TITLE "POLYNOMIAL MODEL FOR WEIGHT VS AGE OF PUMPKINS";
OUTPUT OUT=PUMPKIM_POLY P=yhat_poly;
RUN;

/*********************Program_9_2**************************/
PROC IMPORT OUT=MYOPIA_DATA DATAFILE="/folders/myfolders/data/myopia.xlsx"
			DBMS="xlsx" REPLACE;
			SHEET="myopia1";
			GETNAMES=YES;
RUN;

PROC FORMAT;
VALUE AGEft	low-20="UNDER 20"
			20-29="20 TO 29"
			30-39="30 TO 39"
			40-49="40 TO 49"
			50-59="50 TO 59"
			60-high="60 AND OVER";
RUN;

DATA MYOPIA;
LENGTH PATIENT$ 15;
SET MYOPIA_DATA;
FORMAT AGE AGEft.;
IF lefteye>righteye then PATIENT="LEFT_MYOPIC";
IF righteye>lefteye then PATIENT="RIGHT_MYOPIC";

PROC SORT DATA=MYOPIA;
BY GENDER;
PROC TTEST data=MYOPIA PLOTS=all;
by GENDER;
paired lefteye*righteye;
TITLE "DIFFERENCE BETWEEN LEFT & RIGHT EYE OF PATIENTS WITH MYOPIA";
RUN;

PROC FREQ DATA=MYOPIA;
TABLES GENDER*PATIENT/CHISQ CMH EXACT;
TITLE "ODDS RATIO OF PATIENTS WITH GREATER MYOPIC ON LEFT OR RIGHT EYE";
RUN;

PROC SORT DATA=MYOPIA;
BY AGE;
PROC FREQ DATA=MYOPIA;
TABLES AGE*PATIENT/CHISQ CMH;
TITLE "RISK RATIO OF MYOPIC PATIENTS BY AGE";
RUN;
quit;

Ods Graphics OFF; 
