PROC FORMAT;
VALUE AGEft     4="4 WEEKS OLD"
                6="6 WEEKS OLD"
                8="8 WEEKS OLD"
                10="10 WEEKS OLD"
                12="12 WEEKS OLD";
RUN;

DATA PUMPKIN;
INFILE "/folders/myfolders/data/PUMPKIN.txt" dlm=' ';
DO PUMPKIM=1 TO 24;
    DO AGE= 4 TO 12 by 2;
        AGESQ=AGE**2;
        AGECU=AGE**3;
        INPUT WEIGHT @@;
        OUTPUT;
    END;
END;
FORMAT AGE  AGEft.;

*SCATTER PLOT OF THE ORIGINAL DATA;
Ods Graphics On;
TITLE "SCATTER PLOT OF  WEIGHT_VS_AGE OF PUMPKINS";
proc sgplot data=PUMPKIN;
scatter x=WEIGHT y=AGE;
run;

*LINEAR MODEL;
PROC REG DATA=PUMPKIN ;
MODEL WEIGHT=AGE;
OUTPUT OUT=PUMPKIN_LINEAR P=yhat;
TITLE "LINEAR REGRESSION FOR WEIGHT_VS_AGE OF PUMPKINS";
RUN;

*POLYNOMIAL MODEL;
PROC REG DATA=PUMPKIN  PLOTS=PREDICTIONS(X=AGE);
MODEL WEIGHT = AGE AGESQ AGECU;
TITLE "POLYNOMIAL MODEL FOR WEIGHT VS AGE OF PUMPKINS";
OUTPUT OUT=PUMPKIM_POLY P=yhat_poly;
RUN;

Ods Graphics OFF; 

