/*********************Program_4_1_**************************/
DATA ASTHMA;
INPUT SOC_STATUS$ ASTHMA_IND$ COUNT;
DOUBLECOUNT=COUNT*2;
DATALINES;
LOW YES 40
HIGH YES 30
LOW NO 100
HIGH NO 130
;
PROC FREQ DATA=ASTHMA ORDER=DATA;
TABLES SOC_STATUS*ASTHMA_IND /CHISQ CMH;
WEIGHT COUNT;
RUN;
PROC FREQ DATA=ASTHMA;
TABLES SOC_STATUS*ASTHMA_IND /CHISQ;
WEIGHT DOUBLECOUNT;
RUN;

/*********************Program_4_2_**************************/
DATA VITAMINS;
INPUT USE_VITAMINS$ USE_CONTROL$ VITAMINS_COUNT;

DATALINES;
YES YES 100
YES NO 50
NO YES 90
NO NO 200
;

PROC FREQ DATA=VITAMINS ORDER=DATA;
TABLES USE_VITAMINS*USE_CONTROL /AGREE;
WEIGHT VITAMINS_COUNT;
RUN;

/*********************Program_4_3_**************************/
DATA MEDICAL;
LENGTH MRI$ 12;
INPUT INVASIVE$ MRI$ COUNT;
DATALINES;
OCCLUDED OCCLUDED 15
OCCLUDED NON-OCCLUDED 8
NON-OCCLUDED OCCLUDED 10
NON-OCCLUDED NON-OCCLUDED 67
;
PROC FREQ DATA=MEDICAL ORDER=DATA;
TABLES INVASIVE*MRI/AGREE;
WEIGHT COUNT;
RUN;